name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    uses: minefarts/nightly-pypi-publisher/.github/workflows/run.yml@main
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
